"""Create users and activities tables

Revision ID: c549d7846c90
Revises: 
Create Date: 2022-03-28 03:22:06.864705+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c549d7846c90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'activity_fact',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date_submitted', sa.Date(), nullable=True),
        sa.Column('workout_date', sa.Date(), nullable=True),
        sa.Column('avg_speed_in_mi_per_h', sa.Float(), nullable=True),
        sa.Column('max_speed_in_mi_per_h', sa.Float(), nullable=True),
        sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
        sa.Column('steps', sa.Integer(), nullable=True),
        sa.Column('calories_burned_in_kcal', sa.Integer(), nullable=True),
        sa.Column('distance_in_mi', sa.Float(), nullable=True),
        sa.Column('workout_time_in_seconds', sa.Integer(), nullable=True),
        sa.Column('avg_pace_in_min_per_mi', sa.Float(), nullable=True),
        sa.Column('max_pace_in_min_per_mi', sa.Float(), nullable=True),
        sa.Column('activity_type', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('source', sa.Text(), nullable=True),
        sa.Column('link', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'users',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('username', sa.Text(), nullable=False),
        sa.Column('email', sa.Text(), nullable=False),
        sa.Column('pw_hash', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('activity_fact')
    # ### end Alembic commands ###
