name: CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Package
        run:
          pip install -e .[dev]
      - name: Lint
        run:
          make lint
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Package
      run:
        pip install -e .[dev]
    - name: Typecheck
      run:
        make typecheck
  test:
    name: Test
    runs-on: ubuntu-latest
    container: python:3.10-buster
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ethan_runs
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Package
        run:
          pip install -e .[dev]
      - name: Run test
        env:
          APP_SECRET: ${{ secrets.APP_SECRET }}
          DATABASE_URL: postgresql://postgres:postgres@localhost/ethan_runs
        run:
          make test
